services:
  - type: web
    name: emotional-diary-bot
    env: python
    plan: starter  # Free tier
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    healthCheckPath: /health
    
    # Environment variables (set these in Render dashboard)
    envVars:
      - key: BOT_TOKEN
        sync: false  # Set manually in dashboard
      - key: WEBHOOK_URL
        sync: false  # Set to https://your-app-name.onrender.com (without /webhook)
      - key: DATABASE_URL
        value: sqlite:///./data/emotional_diary.db
      - key: PORT
        value: 8080
      - key: HOST
        value: 0.0.0.0
      - key: LOG_LEVEL
        value: INFO
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PYTHONPATH
        value: /opt/render/project/src
    
    # Disk for persistent SQLite database
    disk:
      name: emotional-diary-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1

# Build settings
buildFilter:
  paths:
  - "**/*.py"
  - requirements.txt
  - render.yaml
  
# Health check settings
healthCheck:
  path: /health
  port: 8080
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
